server:
  port: 8765

spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: DataBase
          uri: http://database:8068/
          predicates:
            - Path=/db/**
        - id: CalculateSession
          uri: http://calculate:8070/
          predicates:
            - Path=/calc/**

path:
  database: database
  calculate: calculate


